[project]
name = "ai-support-ticket-intelligence-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CM", email = "vladtsiperko.2015@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
]

[project.scripts]
ai-support-ticket-intelligence-platform = "ai_support_ticket_intelligence_platform:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
